### ISSUE TITLE
Peerio over Tor?

### ISSUE THREAD

**Issue by ovalseven8** [PeerioTechnologies/peerio-client#11]
Hello,

Thank you for the development of this tool.

I have a question:
Is there an easy way to use Peerio over the Tor-network to make metadata collection more difficult?

Further:
I think most of the Linux user don't use Chrome/Chromium. Because of that a desktop application would make sense.

ovalseven8

**Comment by hdf** [comment]
Peerio server would have to be on the TOR network for that, and Peerio client would have to come with a TOR client itself. I suppose it should be possible, but would probably be much slower, and user's metadata could still be harvested from Peerio servers if seized. DIME (Dark Internet Mail Environment) (formerly Dark Mail) is what will be running on TOR.

It does exist as a desktop application for Windows and Mac, and node-webkit does work on linux as well, not sure, why there is nor folder for that yet.

**Comment by skylarnagao** [comment]
Tested Peerio over Tor by simply directing all my connections to the Tor network. 

Messaging was slightly slower, but still quite usable, even for chat style exchanges. Was able to successfully upload a 98MB file as well, again, a bit slower (about 3-5 minutes), but it worked.

Configuring Peerio to run over the Tor network will definitely be possible, and a "Tor-switch" to auto-configure a Tor connection will be something we look into once proxy controls are implemented.

**Comment by faust64** [comment]
As of ... a few days ago, our app & blobs services are available on Tor. Reaching them, our client needs to query for our onion names instead of app.peerio.com/blob.peerio.com.

We could have our client try resolving our onion FQDN before opening our websocket. If we can resolve onion domains, then we are somehow connected to Tor, we may connect to our Tor FQDN. Otherwise, fallback to our CloudFlare FQDN.
Or just go with that Tor button to trigger the switch?

Alternatively, as of today, would it make sense to move (or at least, duplicate) that issue to the new desktop client?

@anri-asaturov : what would you recommend there?

**Comment by faust64** [comment]
** detecting Tor connectivity, @skylarnagao also mentioned https://check.torproject.org/

**Comment by faust64** [comment]
Disabled CF balancers, Tor clients should no longer be subject to captchas.
Whereas we've started to see fail2ban blocking IPs, ...
