### ISSUE TITLE
Multiple file deletion bug

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#129]
Tried to delete many files, maybe 20-30. Checked them off, clicked delete, four were not deleted and are still checked. If I try to delete again, nothing happens. The files are still downloadable.

**Comment by flohdot** [comment]
I believe the problem is the following: On any multiple-file operation with a large number of files, such as in this case `removeFile`, the client will run out of authTokens and request new ones. However, all the `removeFile` calls will be made in parallel, before the server returns any authTokens, and after a point every single of them will trigger a request for authTokens. If this happens enough times in a row, the server will throttle the requests for authTokens and calls will start failing. 

There are a number of possible fixes, but the simplest seems to be to change the API of `removeFile`, `nukeFile` and `removeConversation` to take an array of IDs in order to use only one authToken for a batch operation. This would require changes on the server as well as on the client (changing the format of the data sent to the server as well as updating error handling to use the new format). @kaepora, please let me know if this works for you or if you think there's a better way to do it.

**Comment by kaepora** [comment]
@flohdot Yes! Let's make `removeFile` and company take an array of IDs.

**Comment by flohdot** [comment]
`removeFile`, `nukeFile` and `removeConversation` now take arrays but still support the old format. This change is available in pre-prod.

**Comment by flohdot** [comment]
Server changes are in prod, and the spec has been pushed.

**Comment by kaepora** [comment]
:star:
