### ISSUE TITLE
Linux client (+ Tails support?)

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#137]
Make Linux client!

**Comment by skylarnagao** [comment]
When building Linux, investigate support for Tails OS (https://tails.boum.org/)

Related to #11

**Comment by skylarnagao** [comment]
Linux client should be uploaded to Debian repository to allow command line install of Peerio: 

Guide for distributing DEB package found here: https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html

**Comment by vdcbb** [comment]
Yes, uploading to Debian/Ubuntu repositories is a good move. It helps authenticate the software as well--ensuring to users that they are downloading from a trusted source.

**Comment by faust64** [comment]
I'm just discovering that issue.
As of today, we're unable to submit our packages to Debian or Ubuntu official repositories (or PPA). The main reason behind this is that NodeJS packages (even in Xenial) come with no node binary, whereas we need it to run npm, pulling our dependencies. If I want to create a link, I need to be in the sudoers of the machine building my packages. When you submit your source package to be built by Debian or Ubuntu's packages building farms, you usually don't have that luxury.
What we did do, is build our packages and distribute them ourselves on linux.peerio.com.
Eventually, I should look into building a source package that pulls nodejs & npm in our build directories.
In terms of "official" repositories, we're on ArchLinux's AUR (which is not official per se, though pretty popular among ArchLinux community), and that's pretty much it.

Debian and Ubuntu packages are signed, our GPG public key and further instructions are available on our repository. Other distributions are supported. Some packages are not signed yet (PeerioTechnologies/peerio-linux-repository#3), mostly all rpm-based ones.
At some point, that GPG key was published to some PPAs' keyserver. Not sure it's still there, since my last failures publishing to PPAs.

As for Tails, we don't have specific packages yet. Depending on the base distributions used building your image, you may already pull one of our Debian clients, granted that you may write your `/usr/share` and `/usr/bin` directories to install it.
Otherwise, I would need to build an image with enough writeable disk space to build our packages, then again you would need `/usr/share` and `/usr/bin` to be writeable installing our package, and your Tails would have to be build on top of the same Debian version I used creating this package.
Finally, considering how Tails is distributed, it would be even easier to distribute our own Tails image embedding our package. Although it is very likely that our image won't include everything you could need. Or may include stuff you won't. And I couldn't blame anyone not to trust a corporate distributing its own Linux distro fork, whereas its main activity is writing a messaging solution -- you don't see LiberOffice distributing VirtualBox templates.

Anyway, what would be our next move? @skylarnagao (or @flohdot )? Can we close that one? Should I focus into publishing to official repositories? What about Tails, would anyone that asked you for this be amenable to build his own image, knowing I can get in touch/help him through?

**Comment by flohdot** [comment]
> Eventually, I should look into building a source package that pulls nodejs & npm in our build directories.

This seems like a good first step, along with #11.

**Comment by faust64** [comment]
next main step addressing lintian warnings would be to replace these
```
E: peerio-client source: source-is-missing application/js/lib/zxcvbn.js
E: peerio-client source: source-is-missing application/js/lib/zepto.js
E: peerio-client source: source-is-missing application/js/lib/sweet-alert.js
E: peerio-client source: source-is-missing application/js/lib/qrcode.js
E: peerio-client source: source-is-missing application/js/lib/pouchdb.js
E: peerio-client source: source-is-missing application/js/lib/papaparse.js
E: peerio-client source: source-is-missing application/js/lib/hotkeys.js
E: peerio-client source: source-is-missing application/js/lib/angular.js
```

Minified js libraries are not considered as sources, I should fetch the original sources instead and minify them during the build process (see http://comments.gmane.org/gmane.linux.debian.devel.mentors/72099).

**Comment by faust64** [comment]
Testing my last changes, I spawned a new instance. Those connected to our VPN may get in touch for further info connecting in. The idea behind running this within our staging setup, is that anyone here may schedule a build and easily test it - which should help us preventing further nss-gate. These won't build source packages, I won't share my GPG key, it is mine, create yours if needed, ... As long as you can build binary packages, you may test, signing is only required when releasing.

Next for me: cleanup warnings building source packages

**Comment by faust64** [comment]
> > Eventually, I should look into building a source package that pulls nodejs & npm in our build directories.

> This seems like a good first step, along with #11.

After further investigations, pulling nodejs at build time wasn't that complicated, and yet is not a viable option, as it turns out we don't even have internet connectivity from the Launchpads VM building binary packages from our submitted sources. Then, even if we did embed some nodejs archive, we would then be missing node modules, and then whatever gulp fetches each time we build our client.

We should consider fixing our build process to prevent gulp/nw-builder to fetch anything. Preferably build whatever is downloaded. We should freeze the node_modules source tree, and build everything later on. It seem like an awful lot of work considering how much and often it may change, .... Unless I'm missing something, we would be building/maintaining tens of npmjs modules ported as deb packages.

**Comment by faust64** [comment]
[log_ubuntu-trusty-amd64.peerio-client_1.4.1-1_BUILDING.txt](https://github.com/PeerioTechnologies/peerio-client/files/243369/log_ubuntu-trusty-amd64.peerio-client_1.4.1-1_BUILDING.txt)

**Comment by faust64** [comment]
Closing. There's not much to do reaching debian/ubuntu official repositories.

Regarding Tails: there's a fair chance at least one of our wheezy, jessie or stretch package would work. It would depend on how your distribution was build. Since there is no versioning in Tails itself, it makes more sense to rely on Debian's versions here.
Installing our client: you would need over 100Mb on your root partitions. Building it, something like 1G (including all build-time dependencies). On Tails, this means you would need to add our package while generating your image.
If I can get in touch with whoever asked for this, we can look for the best alternative together. Otherwise, there's no much point/too much possibles, with no obvious way to distinguish system versions..
