### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by dmp1ce** [PeerioTechnologies/peerio-client#243]
I put in my username and PIN (or passphrase), click login and I get the spinning blue circle forever on the login button.

I'm on version 1.0.4.3

**Comment by anri-asaturov** [comment]
This sounds like a network issue, could you please try again in 10-15 minutes and reply if it's still the case.

**Comment by dmp1ce** [comment]
I'm not sure if it is a network issue. It still won't login for me.

**Comment by dmp1ce** [comment]
Should I get an error message or something?

**Comment by flohdot** [comment]
Any kind of application error should show an error message, yes. Sounds like some networking trouble. Can you tell us a bit more? Are you on a different connection from your usual one(s)? What do you see if you go to https://app.peerio.com in your browser?

**Comment by dmp1ce** [comment]
Yeah, I cannot access the URL either with ping. I am on a VPN through VPN.ht. Maybe my IP is blocked?

**Comment by flohdot** [comment]
Looking into it... Was Peerio over that VPN working previously?

**Comment by dmp1ce** [comment]
It may not have been. I sometimes connect over the VPN and I sometimes don't.

**Comment by dmp1ce** [comment]
I want to say yes, it was previously working over the VPN, but I don't know for sure.

**Comment by flohdot** [comment]
Do you mind filing a ticket with support, with info such as account name, IP you were using, etc? It's hard to debug for sure without precise info. Thanks!

**Comment by flohdot** [comment]
You can add and message the Peerio account 'support'.

**Comment by dmp1ce** [comment]
Sure. No problem. I didn't realize there was a support site. I've created the ticket.

**Comment by nilsws** [comment]
I have the same issue. I've had to reinstall the Mac app for the second time now in a few weeks because I suddenly could not log in anymore. After entering the PIN, the loading indicator would just keep loading. Restarting the app didn't help. Once, after waiting for five minutes, I did get to the message window, but no messages were displayed, so it must be some hickup when loading messages, maybe caching? I've also been using it over VPN some time, but not always. I'm using 1.0.4.3

**Comment by skylarnagao** [comment]
Original issued solved via support.

@nilsws, we experienced a hardware failure on the server last night that resulted in a few hours of downtime. The issue has since been addressed and we will be deploying additional server hardware and  geo-redundant data-centers to mitigate downtime in the future.
