### ISSUE TITLE
Account recovery strategy

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#245]
I'm wondering about account recovery strategy.

Basically a user owns :

1. a minilock key pair
2. a user id

If you loose your minilock private key you loose all your previous stored data (messages and files). So be it. The key is not written down anywhere and I hope all data are not encrypted with an obscure recovery key.

For the user ID, their security is bounded to your account password and 2FA key.

If you loose your password, are you able to reset a password by email ? And if you loose your 2FA key, is there some one time recovery key to keep in case of emergency ?

It's difficult, to find a good recovery strategy without decreasing security. Please, find one without any compromise :D

**Comment by skylarnagao** [comment]
We'll be working on 2FA backup codes and other possible recovery options, e.g. #48

Passphrases are 100% user owned and controlled, so any passphrase / private key recovery or reset from our end is out of the question. For this issue, we're mostly investing in ways to educate users on how to remember their passphrases, as well as develop tools and interfaces that encourage practices that may help users remember their passphrases (even if that amounts to just writing it down on a sheet of paper and storing it somewhere safe).

**Comment by IpsmLorem** [comment]
You can loose your pivate key (i.e. your passphrase) but still be able to recover your username account by email authentication ? And then regenerate a new key pair ?

**Comment by skylarnagao** [comment]
You can recover your username *information* with your email, but Peerio will not allow a new account to be set up with an old username. This is to prevent possible fraud and misrepresentation of old accounts.

e.g. Say I delete the account "skylar", from then on no one can take "skylar". It may be unfortunate for the other Skylars out there, but it also means no one can take my old account name and try to impersonate me.

**Comment by flohdot** [comment]
To elaborate a bit, changing the passphrase for your account after you lost your old one would be _possible_, but we think it is inadvisable for two reasons.

Firstly, after resetting your passphrase, you would not be able to access any of your old files or messages and you would load your Peerio app to find a jumble of data you can no longer decrypt which is still associated to your account. Since no one has your old private key, that data cannot be re-encrypted to use the new keys (as would be the case eventually with an in-app passphrase change where the user does have their old passphrase -- see #89). The UX of going forward with this account would likely be unpleasant.

Secondly, resetting passphrase/keys via email is also a potential attack vector where someone who takes over your email can change your passphrase and lock you out but keep using your account. Despite the identity change warning we provide, there is still plenty of room for user error that we don't want to facilitate.

**Comment by IpsmLorem** [comment]
To sum it up: a lost private key forced the user to create a fresh completely new one. Am I right ?
From a security point a view that's a :+1:

**Comment by flohdot** [comment]
Yup!

**Comment by skylarnagao** [comment]
Marking this as closed, as it seems the resolutions of this topic are available in other tickets so far.
