### ISSUE TITLE
Option to add more words to passphrase

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#250]
Base-line passphrase is roughly 90-bits of entropy, six words with ~15 bits per word (2^15 = 32768 word dictionary)

Add support for up to 10(?) words. Good for users looking for 128+bit passphrases.

**Comment by skylarnagao** [comment]
Added in 1.1.0.

**Comment by fruiz500** [comment]
The app is taking only 5-word keys as of today. This is only 75 bits of entropy at best. They are hard to remember, too, because of the many unusual words.
I suggest allowing users to come up with their own non-dictionary keys, which may have a higher entropy. Accept only those that have an entropy above a certain threshold, say, 75 bits.
You can see an example of how this can be done at the WiseHash page: https://github.com/fruiz500/wisehash

**Comment by skylarnagao** [comment]
Hey @fruiz500, the Peerio app defaults to 5-words, but currently accepts up to 10-word passphrases at the user's discretion. Our estimates put the 5-word dictionary at about 80-bits (including "effective bits" of key stretching). You can read a bit more about our decision to use a 5-word minimum with computer generated phrases [here](http://blog.peerio.com/post/129218816214/build-a-billion-dollar-password).

User selected passphrases is something we're still interested in, but we haven't found a convincing method for evaluating human-chosen entropy. Before we made the shift to computer chosen words we were using [zxcvbn](https://github.com/dropbox/zxcvbn). However, even with fairly high entropy requirements (e.g. ~100-bits), we found that phrases like ```My birthday is January 1st 1980 and my daughter's name is Emily``` we're being accepted. While on paper this might sound reasonable, in real-world scenarios it should be clear that a 100-bit entropy estimate for this phrase is entirely unreasonable — it's easily found basic information about the user entering it.

The problem is that people tend to want to choose passphrases that are familiar to them. It's certainly a tradeoff for those who do feel confident in their password making skills, but we've felt the threat to the less-informed user outweighs the slight inconvenience to the well-versed user.

**Comment by fruiz500** [comment]
I read the blog post. Very informative. After reading it, though, I would like to insist even more strongly that you take a look at the [WiseHash](https://github.com/fruiz500/wisehash) code. It accounts for common character substitutions, use of numbers at predictable locations, and a bunch of other common defects, while zxcvbn does not. It also measures entropy quite accurately so you can use variable key stretching. Variable key stretching works great in practice, since it adds more stretching to the lower entropy passphrases.
I can also offer a pull request where this is done. Just point me to the spot where I should work.

**Comment by anri-asaturov** [comment]
Hi, @fruiz500, phrase generator is here https://github.com/PeerioTechnologies/peerio-client/tree/master/application/js/peerio/phrase
