### ISSUE TITLE
buttons to accept or deny contact request do not appear

### ISSUE THREAD

**Issue by ebilg** [PeerioTechnologies/peerio-client#320]
User reports receiving a contact request but when opening the request is not able to accept or deny because buttons do not appear. 
![buttons to accept or deny contact request do not appear](https://cloud.githubusercontent.com/assets/15635727/11488274/512b0cb0-9793-11e5-815d-0a2ebe3fa836.png)

**Comment by faust64** [comment]
Is 2FA involved?

I've seen something similar using 2FA. Although I haven't disabled it since then, it could be unrelated.
Whenever I leave my client for hours or day, and get a notification: I'm prompted for a new 2FA code; once entered, all messages and contact requests I received are somehow absent.

see https://github.com/PeerioTechnologies/peerio-client/issues/312

I can see the 'new message' or 'new contact' counts, although checking the corresponding view, I don't see anything new.
I tried to open switching tab, opening settings, ... hoping there'ld be some sort of reload. No luck so far.
The only way to "fix" is to restart my client.

**Comment by flohdot** [comment]
I think this might actually have to do with missing display names (or, not missing, but empty strings). To be investigated..

**Comment by ebilg** [comment]
You might be right because the user has tried the following: 
"I did close and open Peerio, logout and login 
many times. I did start Peerio on windows Machine and have the same 
situation - I can't see Accept button. My Frend can't accept me in his 
contact list on the same reason - he can't find accept button. But 
weeks ago we play with Peerio and everething was wprking well."

**Comment by anri-asaturov** [comment]
https://github.com/PeerioTechnologies/peerio-client/commit/9d283826dfd960634fc4f3d9be3ab0bb47e42d85 Fixed. Will be included in next release.
