### ISSUE TITLE
[Linux Packaging] Build Fails on Arch Linux

### ISSUE THREAD

**Issue by zeroedout** [PeerioTechnologies/peerio-client#345]
Hi, trying to build on Arch with no success. Output of makepkg -si [https://gist.github.com/zeroedout/ade40b5ef666373bff6a3bd1866c02e1](url)

I'm not sure what went wrong...

**Comment by faust64** [comment]
Hi,
At first glance, I'm not sure what's going on. I'll give it a look.
Thank you for reporting this.

**Comment by faust64** [comment]
Indeed. Re-building from my former working directory, everything worked. Although wiping it and restarting from scratch, I can reproduce your error.
It does not seem to be related to some archlinux update (I did update & reboot before building my packages). More likely, it's a problem with some NodeJS module that got updated, ... Digging further.

**Comment by faust64** [comment]
Apparently, the `update-dependencies` gulp task is not mandatory (as our `Makefile` already installs dependencies in the application subdir). I've added a new patch to our linux repository, removing that task inclusion in gulp build process, and published a new release to AUR, fetching that new patch instead of the one we used to apply.
Let me know how that goes.

**Comment by faust64** [comment]
I'll assume this is solved, let me know otherwise.
Thanks again for reporting this issue!

**Comment by zeroedout** [comment]
@faust64 Thanks so much! Apologies for taking so long, but it does build now.

**Comment by faust64** [comment]
Sorry for my being late giving it a look. Thank you for your confirmation!
