### ISSUE TITLE
Messages delivered out of order

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#85]
Sending messages too quickly can result in being improperly ordered. 

Received message from "J". 
Sent a response and it appeared above the message received from "J".

Couple other users reported this as well. Exclusively when sending messages quickly in chat style.

**Comment by hdf** [comment]
Are messages Unix timestamped? Maybe they should be?

**Comment by kaepora** [comment]
This is actually a server-side issue.

@flohdot: The server is time-stamping messages. It appears that different Peerio Server instances are time-stamping with bad synchronicity. If I'm connected to `iceking` and my contact is connected to `bubblegum`, and `bubblegum` has a clock that's not synced with `iceking`, timestamps will differ.

I suggest you make sure `ntpd` is set up and configured correctly on all servers. Also, consider looking into `[tlsdate](https://github.com/ioerror/tlsdate)`.

**Comment by flohdot** [comment]
@kaepora did you find any evidence of incorrect timestamping? The servers are, in fact, using NTP so if there's a problem with timestamping it's something else.

I suspect this has more to do with the server _delivering_ messages out of order. Anecdotally, it seems that messages originally listed out of order were reordered correctly upon closing and re-opening of the client, which suggests that the client ordered them by time of arrival rather than timestamp. 

However, I might be wrong about that and will investigate further.

**Comment by kaepora** [comment]
@flohdot Even if messages are delivered out of order, client is still ordering them based on claimed timestamp.

**Comment by skylarnagao** [comment]
Solved.
